services:
   -type: web
    name: ml-flask-api
    env: pyhton
    plan: free
    buildCommon: "pip install -r requiremnets.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    autoDeploy: false # We'll trigger deploys via Github Actions Actions